### ISSUE TITLE
smtpAppender error unhandled when no network present

### ISSUE THREAD

**Issue by smartaz** [log4js-node/smtp#19]
Is it expected for the log4js to quit the process with the following:

log4js.smtpAppender - Error happened { [Error: getaddrinfo ENOTFOUND smtp.gmail.com]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'smtp.gmail.com' }

**Comment by nomiddlename** [comment]
@peteriman good call.

**Comment by lamweili** [comment]
# Background from Node.js
> If an `EventEmitter` does not have at least one listener registered for the `'error'` event, and an `'error'` event is emitted, the error is thrown, a stack trace is printed, and the Node.js process exits.
> _(src: https://nodejs.org/docs/latest/api/events.html#error-events)_

---
# Proposed fix:
A fix would be to add an `error` listener to the `EventEmitter`. 
Can refer to https://github.com/log4js-node/log4js-node/pull/1089/files or below:

https://github.com/log4js-node/smtp/blob/2b122dd92492cfb6019dbc499b0620904dcacf19/lib/index.js#L40

```diff
=L40 const transport = mailer.createTransport(getTransportOptions(config));
+L41 transport.on('error', (e) => {}); // replace with code for error handling
```
---

# Reference details:

Due to nodemailer's `mailer.createTransport` returning [\<Mail\>](https://github.com/nodemailer/nodemailer/blob/master/lib/mailer/index.js) (which is an `EventEmitter`).
Need to add a listener to its `'error'` event (bubbled from `this.transporter`) to prevent Node.js exit.
```javascript
class Mail extends EventEmitter {
```
https://github.com/nodemailer/nodemailer/blob/master/lib/mailer/index.js#L23
```javascript
            // transporter errors
            this.transporter.on('error', err => {
                this.logger.error(
                    {
                        err,
                        tnx: 'transport'
                    },
                    'Transport Error: %s',
                    err.message
                );
                this.emit('error', err);
            });
```

https://github.com/nodemailer/nodemailer/blob/master/lib/mailer/index.js#L73-L84
